import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  preload: true,
})

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#3b82f6',
}

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://buildwise.dev'),
  title: {
    default: 'Buildwise | Custom Websites for Small Businesses',
    template: '%s | Buildwise',
  },
  description:
    'Professional website design and ongoing support for small businesses. Starter $500, Growth $1,000, Pro $2,000. Hosting and maintenance $19/month.',
  keywords: [
    'web design',
    'small business website',
    'website development',
    'web development agency',
    'custom websites',
    'business website',
    'professional web design',
    'website maintenance',
    'web design services',
  ],
  authors: [{ name: 'Buildwise' }],
  creator: 'Buildwise',
  publisher: 'Buildwise',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    siteName: 'Buildwise',
    title: 'Buildwise | Custom Websites for Small Businesses',
    description:
      'Professional website design and ongoing support for small businesses. Starter $500, Growth $1,000, Pro $2,000. Hosting and maintenance $19/month.',
    // OG image is auto-generated by src/app/opengraph-image.tsx
    images: ['/opengraph-image'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Buildwise | Custom Websites for Small Businesses',
    description: 'Professional website design and ongoing support for small businesses.',
    images: ['/opengraph-image'],
    creator: '@buildwise',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: '/',
  },
  category: 'technology',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        {/* Performance: Preconnect to external domains */}
        <link rel="preconnect" href="https://api.web3forms.com" />
        <link rel="dns-prefetch" href="https://api.web3forms.com" />

        {/* Favicons */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <link rel="icon" href="/favicon-16x16.png" type="image/png" sizes="16x16" />
        <link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className="font-sans antialiased">
        <noscript>
          <style>{`.scroll-animate { opacity: 1 !important; transform: none !important; }`}</style>
        </noscript>
        {children}
      </body>
    </html>
  )
}
